name: veil
description: A privacy-focused, AI-enhanced Flutter browser app.
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2
  http: ^1.1.0
  html: ^0.15.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  flutter_local_notifications: ^15.1.0
  flutter_gemini: ^1.0.1
  metadata_fetch: ^0.4.1
  sentiment_dart: ^0.0.5
  gesture_x_detector: ^1.1.1
  flutter_windowmanager: ^0.2.0
  dynamic_color: ^1.6.6
  light: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  settings_ui: ^2.0.2
  webview_cookie_manager: ^2.0.6
  flutter_markdown: ^0.6.17
  share_plus: ^7.1.0
  url_launcher: ^6.1.14
  flutter_inappwebview: ^5.7.2+3
  permission_handler: ^10.4.3
  sqflite: ^2.3.0
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  uuid: ^3.0.7
  connectivity_plus: ^4.0.2
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.0
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
